name: SAST-SCA-SBOM

# Running SCA Agent against Repo
on:
  workflow_dispatch:

jobs:
  SCA-Agent-Scan-Results-Import:
    runs-on: ubuntu-latest
    steps:
    # Running Software Composition Analysis Agent against the local repo and the container
      # Checkout code
      - uses: actions/checkout@v3
      - name: List folder contents for visual to confirm artifact file exists
        run: |
          ls -la
    
      #SCA Agent against repo
      - name: Veracode SCA Agent Dependency Scanning
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2
        with:
          github_token: ${{ github.token }}
          update_advisor: true
          create-issues: true
        # A path within the repository where the build definition starts
          path: app
        # Run the SRCCLR with the `--allow-dirty` option
          allow-dirty: true 

      - name: Upload artifact with SCA app and container issues for this build
        uses: actions/upload-artifact@v3.1.1
        with:
           name: SCA-Issues-VeraDemoDotNetCore-${{ github.run_id }}
           path: "*.json"      
